### ISSUE TITLE
CC2015 June update breaks grunt-cep

### ISSUE THREAD

**Issue by MattMcNam** [fcamarlinghi/grunt-cep#15]
The updated apps released a few days ago have in some (all?) cases had a major version bump (Prelude is now 5.0, Photoshop is 17.0 etc.) which breaks the manifests, and the application paths have also changed at least on OS X to now have `... CC 2015.x` in the file path, but not 100% consistently as shown in these examples:
`Adobe Prelude CC 2015.4/Adobe Prelude CC 2015.app`
`Adobe Photoshop CC 2015.5/Adobe Photoshop CC 2015.5.app`
... which breaks the launch profile.

For manifests, a simple fix could be to just set the minimum version rather than a range, as shown here: https://github.com/Adobe-CEP/CEP-Resources/issues/60#issuecomment-227858667.

The other option would be to make a new family, `CC2015.5`?
It's hard to decide as only Photoshop and Illustrator are on CEP7, the rest are still CEP6.1 but have these changed major versions and paths. 
Not sure about the best option so I'm opening as a conversation

**Comment by fcamarlinghi** [comment]
Thanks for opening up this issue. I finally had a chance to take a look at the new release... For some reason Adobe really likes to make life harder for plugin developers with every release! :/

Adobe refers to CC2015.5 as CC2016 in the latest [CEP Extension Cookbook](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_7.x/CEP_7.0_HTML_Extension_Cookbook.pdf), so I guess we won't see a CC2016 release this year, but it might be better to have a new _CC 2015.5_ family to be as failsafe as possible. Having a new family would also help with the changed paths.

Here's a list of the updated products from the cookbook alongside the CEP version they support (products that have had a major version upgrade are in bold):

_CC 2015 &rarr; CC 2015.5_
**Photoshop 16  &rarr; 17** (CEP 7.0)
InDesign 11 &rarr; 11 (CEP 6.1)
InCopy 11 &rarr; 11 (CEP 6.1)
**Illustrator 19 &rarr; 20**  (CEP 7.0)
**Premiere Pro 9 &rarr; 10** (CEP 6.1)
**Prelude 4 &rarr; 5** (CEP 6.1)
After Effects 13 &rarr; 13 (CEP 6.1)
Flash Pro 15 &rarr; 15 (CEP 6.1)
**Audition 8 &rarr; 9** (CEP 6.1)
Dreamweaver 16 &rarr; 16 (CEP 6.1)

Given that most applications are still on CEP6.1 (and that both Photoshop and Illustrator should continue to support CEP 6.1 plugins), I think it should be safe to keep that as the default. Users who need CEP 7.0 would only need to do a minor tweak to the templates. In order to support debugging for both CEP 6.1 and 7.0, both the PlayerDebugMode flags for 6 and 7 should be set though.

About the file paths, it seems they have changed on Windows too. Unfortunately at the moment I don't have access to a subscription that include all applications so I'm not able to find out all the new paths. Can you please share the paths for the applications you have access to?

I was not aware of the minimum version instead of a range. It could make things more future proof and also simplify the code a bit. The only issue I see is that we'll lose the ability to have different versions of an extension that targets different version ranges of the an application in the same package. It surely is an edge case, but I wouldn't like to break user's plugins that might rely on that.
