### ISSUE TITLE
Watch a folder and copy to extension

### ISSUE THREAD

**Issue by Vontus** [fcamarlinghi/grunt-cep#28]
I can't figure out how I can make grunt-cep copy a folder to the extension installation folder whenever it is changed. It is possible to do? It already does when running the cep task, but I need to update it every time it is modified without having to relaunch the host app.

**Comment by fcamarlinghi** [comment]
Unfortunately what you describe isn't possible with grunt-cep in part due to the way the "launch" profile works, and in part because the host app, once it's open, will lock some files (such as extension manifests and icons) preventing any changes to them. Making changes to HTML/JS/JSX files should be possible, but will still require a manual refresh of the extension window/panel to make sure the host app picks them up.

Some possible workarounds:
1) Launch the host app using grunt-cep and then have another grunt task copy updated files to the extension folder every time they change.
2) Once grunt-cep has generated the extension folder, move it to a location of your choice and use that folder for your development. Then create a symbolic link between that folder and the local Adobe CEP extensions folder on your system. This way the changes you make in your development folder will be reflected in the extension folder automatically by the filesystem.
