### ISSUE TITLE
How to package extension on CI env based on OS Linux ?

### ISSUE THREAD

**Issue by vdeygas** [fcamarlinghi/grunt-cep#33]
Hello,

I search for a solution/idea to sign my CC extension on a continuous integration build environnement.

This env. is based on OS linux.

Thank you very much,

porcinet

**Comment by fcamarlinghi** [comment]
Hello, integrating _grunt-cep_ in CI should be as simple as running the _package_ profile from the command line. However, I think you'll need either a Windows or Mac environment as the ZXPSignCmd tool by Adobe used to sign and package extensions, is [only available there](https://github.com/Adobe-CEP/CEP-Resources/tree/master/ZXPSignCMD/4.0.7).

**Comment by vdeygas** [comment]
Thanks for your reply.

I'm agree that it is doable on Windows / CI.
But, solution I'm seaching for should be based on linux.

I've seen Mono (https://www.linux.com/news/running-net-applications-linux-mono), but ZXPsignCmd.exe is not

Before ZXPSignCmd, I remember using ucf.jar. Why not use this jar and sign method for CEP extension ?

Thx

**Comment by fcamarlinghi** [comment]
ucf.jar was used to sign Flash-based extensions, but it has been superseded by ZXPSignCmd starting with CC. I'm unsure as to whether or not extensions packaged with ucf.jar can be used with CC products.  I think your best bet is to try and, if that works for you, fork _grunt-cep_ and [make it use ucf.jar](https://github.com/fcamarlinghi/grunt-cep/blob/24280ab8ee270c0df11a25ff8120f5917fb94f58/tasks/lib/zxp.js#L76) instead of ZXPSignCmd.

Regarding how to run ZXPSignCmd on Linux, I'm sorry but I can't be of much help (maybe you can try asking on the [Adobe forums](https://forums.adobe.com/community/creative_cloud/add-ons/extensions)?).
