### ISSUE TITLE
"grunt cep:package" ignores staging path

### ISSUE THREAD

**Issue by Vontus** [fcamarlinghi/grunt-cep#35]
The command **grunt cep:package** always generates the output at **\<project folder\>/staging** and ignores the staging path option given in the cep-config.js file.

That option only works with **grunt cep:debug**, I think it sould work with **grunt cep:package** too, or add another way to configure the folder for the package output.

**Comment by fcamarlinghi** [comment]
Hello! The following configuration seems to work fine for me:

```js
module.exports = function (grunt)
{
    grunt.initConfig({
        cep: {

            // ...

            release: {
                options: {
                    profile: 'package',
                    staging: 'foo/bar'
                },
            },
        },
    });

    grunt.loadNpmTasks('grunt-cep');
};
```

The output ZXP as well as the temporary folders are generated at `<project folder>/foo/bar` as expected when running the `grunt cep:release` task.

Can you please share your Gruntfile?

**Comment by Vontus** [comment]
I was using this in my cep-config.js
```
builds: [
    // CC2019
    {
      bundle: { manifest: 'bundle/manifests/manifest.bundle.cc2019.xml' },
      products: ['illustrator'],
      staging: 'cep-generated/staging',
      source: 'cep-generated/output',
      families: ['CC2019']
    }
]
```
Why is this config only used for debug mode?

**Comment by fcamarlinghi** [comment]
The code you're using works in debug because only a single build gets compiled (i.e. the one you want to debug). As such, the build config is merged with the task options and used to generate the output.

When _grunt-cep_ prepares your bundle for release, it first compiles each build and packages it into its own ZXP file. It then copies any additional files (i.e. to support hybrid extensions) to the same folder and finally packages everything in a single ZXP for distribution. As such, a single staging folder is used for all the builds.

I agree that this is somewhat counter-intuitive and it's the result of an aging codebase, but I don't see any easy way to support what you're trying to do without some major rewrite of the plugin (which is unlikely to happen in the near future).

**Comment by Vontus** [comment]
Understood! Thank you for your help!
