### ISSUE TITLE
Problem with ZXPSignCmd on Debian 9

### ISSUE THREAD

**Issue by Lilipi** [fcamarlinghi/grunt-cep#36]
Hi,
I cannot sign my zxp on my Debian 9 because of a problem on a module that you use to get ZxpSignCmd path/executable (zxp-provider).
I've opened an issue on that project too (https://github.com/codearoni/zxp-provider/issues/13).

A workaround for me would be to be able to pass as a parameter the "zxp_path" that you use on your command to sign zxp. In fact, I have a ZXPSignCmd on my Debian that works well ! (Using an exe and wine command)
If I work on it to add that as a parameter ; would you accept my PR ? (I don't want to work on it for nothing 😉 )

Thanks !

**Comment by fcamarlinghi** [comment]
As the author of _zxp-provider_ pointed out in the issue you opened on that project, ZXPSignCmd only supports Windows and Mac. Running the Windows version through Wine it's more of an hack rather than a proper solution and, although it might work for you, there's no guarantees that it will work for others (i.e. on a different Linux distribution, using a different Wine version, for future versions of ZXPSignCmd, etc.).

As such, it's unlikely I'll accept a PR adding support for that, especially if it means adding additional parameters to the API (which is already kind of complex). Since the version of ZXPSignCmd you need to run is strictly related to the environment, I think a better approach would be to leverage environment variables. The best place to implement something like that, however, would be inside the _zxp-provider_ package rather than in _grunt-cep_ directly.
